import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MockService {

  constructor() { }
  userData:any={
    "Clients": {
      "clients": [
        {
          "CEL": true,
          "Issue": false,
          "clientId": 175,
          "gfiId": "552",
          "iasoId": "106161",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "18 Week Support",
          "nodeId": null,
          "reviewDate": null,
          "tag": "18WS",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 200,
          "gfiId": "654",
          "iasoId": "218580",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "23 Capital Management Limited",
          "nodeId": null,
          "reviewDate": null,
          "tag": "23CA",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 160,
          "gfiId": "258",
          "iasoId": "66163",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "2h Wealthcare LLP",
          "nodeId": null,
          "reviewDate": null,
          "tag": "2HWC",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 19,
          "gfiId": "268",
          "iasoId": "4152",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "33SIX Consulting Ltd",
          "nodeId": "36922890",
          "reviewDate": null,
          "tag": "33SX",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 258,
          "gfiId": "1028",
          "iasoId": "2457302",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "4 New Square",
          "nodeId": null,
          "reviewDate": null,
          "tag": "4NSQ",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": true,
          "clientId": 34,
          "gfiId": "301",
          "iasoId": "49752",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": true,
          "isInternalTicketEmail": true,
          "name": "Acme Corporation (Testing)",
          "nodeId": "36721518",
          "reviewDate": null,
          "tag": "ACME",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 266,
          "gfiId": "1064",
          "iasoId": "2467064",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "ACS International Schools",
          "nodeId": null,
          "reviewDate": null,
          "tag": "ACSS",
          "teamId": 4,
          "teamName": "Panacea",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 236,
          "gfiId": "877",
          "iasoId": "2161861",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "AG Thames (AGT)",
          "nodeId": null,
          "reviewDate": null,
          "tag": "AGTL",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 139,
          "gfiId": "175",
          "iasoId": "142848",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Akur",
          "nodeId": null,
          "reviewDate": null,
          "tag": "AKUR",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 23,
          "gfiId": "300",
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Alfred Franks and Bartlett",
          "nodeId": "37380665",
          "reviewDate": null,
          "tag": "AFBL",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 217,
          "gfiId": "734",
          "iasoId": "346604",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Alliance Asset Management (AAM)",
          "nodeId": null,
          "reviewDate": null,
          "tag": "AAML",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 154,
          "gfiId": "139",
          "iasoId": "61092",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Amazon Property Limited",
          "nodeId": null,
          "reviewDate": null,
          "tag": "AMAZ",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 2,
          "gfiId": "274",
          "iasoId": "41183",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "APM Group Limited",
          "nodeId": null,
          "reviewDate": null,
          "tag": "APMG",
          "teamId": 4,
          "teamName": "Panacea",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 26,
          "gfiId": "126",
          "iasoId": "4136",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "ASC Financial Solutions",
          "nodeId": null,
          "reviewDate": null,
          "tag": "ASCF",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 223,
          "gfiId": "762",
          "iasoId": "504586",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Asthma UK and British Lung Foundation Partnership (AUK/BLF)",
          "nodeId": null,
          "reviewDate": null,
          "tag": "TBLF",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 31,
          "gfiId": "157",
          "iasoId": "4137",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Astor Court Hotel",
          "nodeId": "36922926",
          "reviewDate": null,
          "tag": "ASCH",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 188,
          "gfiId": "614",
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "ATTRAQT",
          "nodeId": null,
          "reviewDate": null,
          "tag": "ATTR",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 231,
          "gfiId": "818",
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Bethlem Gallery Projects",
          "nodeId": null,
          "reviewDate": null,
          "tag": "BGAL",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 9,
          "gfiId": "138",
          "iasoId": "20282",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Big Red Recruitment",
          "nodeId": "36897971",
          "reviewDate": null,
          "tag": "BIGR",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 30,
          "gfiId": "204",
          "iasoId": "41670",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Blue Earth Diagnostics Limited",
          "nodeId": "60335768",
          "reviewDate": null,
          "tag": "BEDG",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 259,
          "gfiId": null,
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Blue Skies Partnership",
          "nodeId": null,
          "reviewDate": null,
          "tag": "BSPL",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 204,
          "gfiId": null,
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Bluecube Commissions",
          "nodeId": null,
          "reviewDate": null,
          "tag": "BLUE",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 1,
          "gfiId": "100",
          "iasoId": "2364588",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Bluecube Technology Solutions",
          "nodeId": null,
          "reviewDate": null,
          "tag": "BTSL",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 244,
          "gfiId": null,
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Bristow and Sutor",
          "nodeId": null,
          "reviewDate": null,
          "tag": "BRIS",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 153,
          "gfiId": null,
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "BSH Home Appliances",
          "nodeId": null,
          "reviewDate": null,
          "tag": "BSHG",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 292,
          "gfiId": null,
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "BTO Solicitors",
          "nodeId": null,
          "reviewDate": null,
          "tag": "BTOS",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 40,
          "gfiId": "232",
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "C & D Partnership Ltd",
          "nodeId": null,
          "reviewDate": null,
          "tag": "CDPR",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 42,
          "gfiId": "46218",
          "iasoId": "4143",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Carbon Registry Services",
          "nodeId": null,
          "reviewDate": null,
          "tag": "CRSV",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 222,
          "gfiId": null,
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "CCN Communications",
          "nodeId": null,
          "reviewDate": null,
          "tag": "CCNC",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 203,
          "gfiId": "661",
          "iasoId": "243489",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "CE Mining",
          "nodeId": null,
          "reviewDate": null,
          "tag": "CEMI",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 189,
          "gfiId": "612",
          "iasoId": "145279",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Cifas",
          "nodeId": null,
          "reviewDate": null,
          "tag": "CIFA",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 41,
          "gfiId": "284",
          "iasoId": "4156",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Citius",
          "nodeId": "36922934",
          "reviewDate": null,
          "tag": "CTUS",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 43,
          "gfiId": "167",
          "iasoId": "56286",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Clinica London Limited",
          "nodeId": null,
          "reviewDate": null,
          "tag": "CLIN",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 199,
          "gfiId": null,
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Control Print",
          "nodeId": null,
          "reviewDate": null,
          "tag": "CTRL",
          "teamId": 1,
          "teamName": "Atlantis",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 228,
          "gfiId": "811",
          "iasoId": "2030083",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Costello Medical",
          "nodeId": null,
          "reviewDate": null,
          "tag": "COST",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 267,
          "gfiId": "1061",
          "iasoId": "2481389",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Creations Interiors Ltd",
          "nodeId": null,
          "reviewDate": null,
          "tag": "CRIN",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 161,
          "gfiId": "783",
          "iasoId": "89717",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Dalcour Maclaren Limited",
          "nodeId": null,
          "reviewDate": null,
          "tag": "DALM",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 12,
          "gfiId": "132",
          "iasoId": "13022",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "DAO Maritime Ltd",
          "nodeId": "37206466",
          "reviewDate": null,
          "tag": "DAOM",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 182,
          "gfiId": null,
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Demo Client",
          "nodeId": null,
          "reviewDate": null,
          "tag": "DEMO",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 243,
          "gfiId": null,
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Department for International Trade",
          "nodeId": null,
          "reviewDate": null,
          "tag": "DFIT",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 47,
          "gfiId": "295",
          "iasoId": "36390",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Different Strokes (Trustees) Ltd",
          "nodeId": null,
          "reviewDate": null,
          "tag": "DIFS",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 255,
          "gfiId": "1023",
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Digby Brown",
          "nodeId": null,
          "reviewDate": null,
          "tag": "DIGB",
          "teamId": 6,
          "teamName": "Soteria",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 50,
          "gfiId": "633",
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Diner Management",
          "nodeId": null,
          "reviewDate": null,
          "tag": "DINE",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 151,
          "gfiId": null,
          "iasoId": "88515",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Direct Cloud Backup",
          "nodeId": null,
          "reviewDate": null,
          "tag": "DCBK",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 185,
          "gfiId": null,
          "iasoId": "80986",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": false,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Direct Cloud Backup - Headtech",
          "nodeId": null,
          "reviewDate": null,
          "tag": "DCBH",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 184,
          "gfiId": null,
          "iasoId": "125698",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": false,
          "isHavingPrimarySiteContact": false,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Direct Cloud Backup - KeeServices",
          "nodeId": null,
          "reviewDate": null,
          "tag": "DCBS",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 205,
          "gfiId": "689",
          "iasoId": null,
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "discover.ai",
          "nodeId": null,
          "reviewDate": null,
          "tag": "DISC",
          "teamId": 2,
          "teamName": "Nautilus",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 213,
          "gfiId": "721",
          "iasoId": "314746",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Ecology Solutions",
          "nodeId": null,
          "reviewDate": null,
          "tag": "ECOL",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": false,
          "Issue": false,
          "clientId": 209,
          "gfiId": null,
          "iasoId": "303545",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "Efficio",
          "nodeId": null,
          "reviewDate": null,
          "tag": "EFIC",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        },
        {
          "CEL": true,
          "Issue": false,
          "clientId": 55,
          "gfiId": "133",
          "iasoId": "22367",
          "isActive": true,
          "isContactUpdateReminder": false,
          "isHavingCSTUsers": true,
          "isHavingPrimarySiteContact": true,
          "isInternalTicket": false,
          "isInternalTicketEmail": false,
          "name": "EFile",
          "nodeId": "36932520",
          "reviewDate": null,
          "tag": "EFLE",
          "teamId": 3,
          "teamName": "Watchtower",
          "totalCount": 145
        }
      ],
      "totalClientsCount": 145
    },
    "Errors": []
  }
  
}
